# Generated by Django 5.2.4 on 2025-07-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_remove_watchlist_active_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
